# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_build_args: "--no-build-vignettes"
r_check_args: "--no-examples --no-tests --no-vignettes --no-manual"

addons:
  apt:
    packages:
    - libmagick++-dev
services:
  - xvfb
after_success:
  - Rscript -e 'covr::codecov()'
